# Andrej Karpathy's /nanoGPT

#### Reference
https://www.youtube.com/watch?v=kCc8FmEb1nY

https://github.com/karpathy/nanoGPT

chatgPT is another language model that completes a given sentence. The generative AI comes from "Attention Is All You Need" paper. 

In this module we'll build a char level language model based on the transformer's architecture. The dataset is the entire work of shakespeare. The model will generate, shakespeare-like text.

In [1]:
with open('tiny-shakespeare.txt', 'r') as f:
    text = f.read()

In [2]:
print("length of dataset in char: ", len(text))

length of dataset in char:  1115394


In [3]:
# here is our vocabulary; all possible characters in the text
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print('vocab size: ', vocab_size)


 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
vocab size:  65


In [4]:
# tokenize the text
s2i = {ch:i for i,ch in enumerate(chars)}
i2s = {i:ch for i,ch in enumerate(chars)}
encode = lambda s: [s2i[ch] for ch in s] # encoder: take a string and return a list of integers
decode = lambda x: ''.join([i2s[i] for i in x]) # decoder: take a list of integers and return a string

print(encode("hi there"))
print(decode(encode("hi there")))

[46, 47, 1, 58, 46, 43, 56, 43]
hi there


there are many tokenizing algorithms. Google uses ```SentencePiece``` which is a sub-word-unit tokenizer; it's not char level, nor word level.  OpenAi uses ```tiktoken```.

import tiktoken
enc = tiktoken.gen_encoding("gpt2")
assert enc.decode(enc.encode("hello world')) == "hello world"

with these tokenizers you won't get a long list of int. it helps to get a smaller list with larger word vocab sizes.


In [5]:
# let's now encode the entire text dataset and store it in a torch.Tensor
import torch
data = torch.tensor(encode(text), dtype=torch.long)

print(data.shape, data.dtype)
print(data[:100])

torch.Size([1115394]) torch.int64
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59])


In [7]:
# let's split the data into train and validation sets to understand if our model is overfitting
n = int(0.9*len(data)) # first 90% of the data
train_data = data[:n]
val_data = data[n:]

for training the NN we need to train on chunks of data, otherwise it's not optimal to feed in the entire data. that's why we use ```block_size```.

In [8]:
block_size = 8
train_data[:block_size+1]

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])

think about the training process as follows: 

when a token of value '18' is provided, there is a high chance to generate '47'.

when a token of value '18 47' is provided, there is a high chance to generate '56'.

when a token of value '18 47 56' is provided, there is a high chance to generate '57'.

...

In [11]:
torch.manual_seed(1337) # this is for reproducibility to get the same results every time
batch_size = 4 # how many independent sequences to process in parallel
block_size = 8 # the max context length for predictions

def get_batch(split):
    # generate small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,)) # random start indices for the examples
    x = torch.stack([data[i:i+block_size] for i in ix]) # batch_size x block_size
    y = torch.stack([data[i+1:i+block_size+1] for i in ix]) # batch_size x block_size
    return x, y


In [12]:
xb, yb = get_batch('train')
print('inputs: ')
print(xb.shape)
print(xb)
print('targets: ')
print(yb.shape)
print(yb)

print('-------')

inputs: 
torch.Size([4, 8])
tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])
targets: 
torch.Size([4, 8])
tensor([[43, 58,  5, 57,  1, 46, 43, 39],
        [53, 56,  1, 58, 46, 39, 58,  1],
        [58,  1, 58, 46, 39, 58,  1, 46],
        [17, 27, 10,  0, 21,  1, 54, 39]])
-------


In [13]:
# visualize the way the input and target are generated
for b in range(batch_size):
    for t in range(block_size):
        context = xb[b, :t+1]
        target = yb[b, t]
        print(f'when input is {context.tolist()}, target is {target}')

when input is [24], target is 43
when input is [24, 43], target is 58
when input is [24, 43, 58], target is 5
when input is [24, 43, 58, 5], target is 57
when input is [24, 43, 58, 5, 57], target is 1
when input is [24, 43, 58, 5, 57, 1], target is 46
when input is [24, 43, 58, 5, 57, 1, 46], target is 43
when input is [24, 43, 58, 5, 57, 1, 46, 43], target is 39
when input is [44], target is 53
when input is [44, 53], target is 56
when input is [44, 53, 56], target is 1
when input is [44, 53, 56, 1], target is 58
when input is [44, 53, 56, 1, 58], target is 46
when input is [44, 53, 56, 1, 58, 46], target is 39
when input is [44, 53, 56, 1, 58, 46, 39], target is 58
when input is [44, 53, 56, 1, 58, 46, 39, 58], target is 1
when input is [52], target is 58
when input is [52, 58], target is 1
when input is [52, 58, 1], target is 58
when input is [52, 58, 1, 58], target is 46
when input is [52, 58, 1, 58, 46], target is 39
when input is [52, 58, 1, 58, 46, 39], target is 58
when input i

in bigram model for instance, the prediction was only based on the last charr. However, thee history or chars/tokens that came before also has a impact on choosing the next char. That's when transformer model comes into the picture.

the easiest way to get info about the previous tokens is to sum their channel values and average it. obviously this will loose a lott of info on the spacial information about the tokens, but we'll address that later.

the technique for averaging over previous tokens is called ```bag of words```.

In [15]:
# consider this toy example

torch.manual_seed(1337)
B, T, C = 4, 8, 2 # batch, time, channels
x = torch.randn(B, T, C)
x.shape

torch.Size([4, 8, 2])

In [17]:
# Version 1: use for loops for averaging

# we want x[b, t] = mean _ {i<=t} x[b, i]
xbow = torch.zeros((B, T, C)) # x bag of words. a word is on each of the 8 locations and we are averaging
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] # (t, c)
        xbow[b, t] = torch.mean(xprev, 0)

to be efficient about this averaging we can use matrix multiplications. we'll build a matrix 'a' such that, multiplying another matrix by it, would generate a new matrix where each row represents the average of elements in previous rows, column-wise.

In [29]:
torch.manual_seed(42)
a = torch.tril(torch.ones((3, 3)))
a = a / torch.sum(a, 1, keepdim=True)
b = torch.randint(0,10,(3,2)).float()
c = a @ b

print(a)
print(b)
print(c)

tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [30]:
# Version2: use matrix multiplication

wei = torch.tril(torch.ones((T, T))) # weight matrix
weil = wei / wei.sum(1, keepdim=True)
xbow2 = weil @ x

#validate to make sure xbow and xbow2 are the same
torch.allclose(xbow, xbow2)


True

In [32]:
# Version 3: use softmax

import torch.nn.functional as F
tril = torch.tril(torch.ones((T, T)))
wei = torch.zeros((T, T))
wei = wei.masked_fill(tril == 0, float('-inf')) # make all the zeros -inf
wei = F.softmax(wei, 1) # exponentiate and divide by sum
xbow3 = wei @ x

# validate 
torch.allclose(xbow, xbow3)

True

In [39]:
# Version 4: self-attention
import torch.nn as nn
torch.manual_seed(1337)
B, T, C = 4, 8, 2 # batch, time, channels
x = torch.randn(B, T, C)

# let's see a single head perform self-attention
head_size = 16
key =   nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
k = key(x)   # (B, T, 16)
q = query(x) # (B, T, 16)
wei = q @ k.transpose(-2, -1) # transpose the last two columns. (B, T, 16) @ (B, 16, T) = (B, T, T)

tril = torch.tril(torch.ones((T, T)))
wei = wei.masked_fill(tril == 0, float('-inf')) # make all the zeros -inf. if you are for instance trying to do sentiment analysis, you can remove this line so all the nodes get to talk to each other
wei = F.softmax(wei, 1) # exponentiate and divide by sum
out = wei @ x

wei[0]

tensor([[0.1316, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1215, 0.0814, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1467, 0.0783, 0.2508, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1593, 0.0674, 0.3324, 0.5611, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1262, 0.1577, 0.1347, 0.1402, 0.2156, 0.0000, 0.0000, 0.0000],
        [0.0913, 0.1651, 0.0511, 0.0325, 0.2371, 0.2694, 0.0000, 0.0000],
        [0.1351, 0.0838, 0.1934, 0.2463, 0.4575, 0.0160, 0.6153, 0.0000],
        [0.0882, 0.3662, 0.0376, 0.0200, 0.0898, 0.7147, 0.3847, 1.0000]],
       grad_fn=<SelectBackward0>)

Notes:
- Attention is a **communication mechanism**. Can be seen as nodes in a directed graph looking at each other and aggregating information with a weighted sum from all nodes that point to them, with data-dependent weights.
- There is no notion of space. Attention simply acts over a set of vectors. This is why we need to positionally encode tokens.
- Each example across batch dimension is of course processed completely independently and never "talk" to each other
- In an "encoder" attention block just delete the single line that does masking with `tril`, allowing all tokens to communicate. This block here is called a "decoder" attention block because it has triangular masking, and is usually used in autoregressive settings, like language modeling.
- "self-attention" just means that the keys and values are produced from the same source as queries. In "cross-attention", the queries still get produced from x, but the keys and values come from some other, external source (e.g. an encoder module)
- "Scaled" attention additional divides `wei` by 1/sqrt(head_size). This makes it so when input Q,K are unit variance, wei will be unit variance too and Softmax will stay diffuse and not saturate too much. Illustration below

### Full finished code, for reference

You may want to refer directly to the git repo instead though.a

In [43]:
import torch
import torch.nn as nn
from torch.nn import functional as F

# hyperparameters
batch_size = 16 # how many independent sequences will we process in parallel?
block_size = 32 # what is the maximum context length for predictions?
max_iters = 5000
eval_interval = 100
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 64
n_head = 4
n_layer = 4
dropout = 0.0
# ------------

torch.manual_seed(1337)

# wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
with open('tiny-shakespeare.txt', 'r', encoding='utf-8') as f:
    text = f.read()

# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

# Train and test splits
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)   # (B,T,C)
        q = self.query(x) # (B,T,C)
        # compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * C**-0.5 # (B, T, C) @ (B, C, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,C)
        out = wei @ v # (B, T, T) @ (B, T, C) -> (B, T, C)
        return out

class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

# super simple bigram model
class BigramLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = BigramLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))


0.209729 M parameters
step 0: train loss 4.4116, val loss 4.4022
step 100: train loss 2.6568, val loss 2.6670
step 200: train loss 2.5091, val loss 2.5058
step 300: train loss 2.4194, val loss 2.4335
step 400: train loss 2.3500, val loss 2.3561
step 500: train loss 2.2964, val loss 2.3129
step 600: train loss 2.2409, val loss 2.2500
step 700: train loss 2.2053, val loss 2.2187
step 800: train loss 2.1630, val loss 2.1863
step 900: train loss 2.1236, val loss 2.1501
step 1000: train loss 2.1031, val loss 2.1298
step 1100: train loss 2.0694, val loss 2.1188
step 1200: train loss 2.0390, val loss 2.0802
step 1300: train loss 2.0245, val loss 2.0636
step 1400: train loss 1.9943, val loss 2.0378
step 1500: train loss 1.9700, val loss 2.0303
step 1600: train loss 1.9643, val loss 2.0491
step 1700: train loss 1.9418, val loss 2.0127
step 1800: train loss 1.9092, val loss 1.9953
step 1900: train loss 1.9095, val loss 1.9885
step 2000: train loss 1.8840, val loss 1.9936
step 2100: train loss 1.